### ISSUE TITLE
Posting a comment via Kentico Xperience administration interface

### ISSUE THREAD

**Issue by TereziaZ** [Kentico/xperience-disqus#6]
Posting a Disqus comment in Pages app in the Kentico Xperience administration interface throws an error.

**Steps to reproduce the behavior:**
1. Add a Disqus widget to a page
2. Access this page in Pages app in the Kentico Xperience administration
3. Still in the Pages app, post a Disqus comment via this widget
4. A 404 error is logged in the Browser console, an error is logged in the Event log app
5. The comment is saved though

**Comment by kentico-ericd** [comment]
I see that the error is `VirtualContextHashValidationFailed` occurring on _/cmsctx/[...]/-/~/kentico.xperience.disqus/LogCommentActivity_. My question is, would you expect an On-line Marketing activity to be logged when an authenticated Xperience user posts a comment from the page builder? I would no since it is not a "real" contact, but I'm not sure what the full use-cases are.

I suppose if someone were tracking "comments per page" in the __Reporting application__ for example, not logging this would throw off the metrics. In that case, I guess this should be fixed and not avoided by preventing logging. Thoughts?

**Comment by KubaOczko** [comment]
We're blocking online marketing features outside of the live site because we don't want to track content editors... In this case, we should extend the [condition](https://github.com/Kentico/xperience-disqus/blob/master/src/Views/Shared/Components/DisqusComponent/Default.cshtml#L19) in the component view to also check the edit mode
